### ISSUE TITLE
Prevent account enumeration

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/jobboard#12]
By going to http://jobs.techlahoma.org/login, I can punch in any email address to see if someone has an account.

This could potentially be sensitive information - e.g., for stealth-mode start-ups, or currently-employed job-seekers.

**Comment by vlucas** [comment]
Job seekers don't have to signup for an account, but I do get this. This was a tradeoff to make the service more usable since it does not currently have any password reset or forgot password features.

**Comment by jagthedrummer** [comment]
I think ideally we don't want to be in the business of storing passwords.
Using OAUTH to let people connect with Twitter or GitHub would allow us to
skip passwords entirely.

On Nov 26, 2016 9:42 PM, "Vance Lucas" <notifications@github.com> wrote:

Job seekers don't have to signup for an account, but I do get this. This
was a tradeoff to make the service more usable since it does not currently
have any password reset or forgot password features.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/techlahoma/jobboard/issues/12#issuecomment-263098811>,
or mute the thread

**Comment by groovecoder** [comment]
For job board, maybe GitHub + LinkedIn ?

**Comment by vlucas** [comment]
@jagthedrummer @groovecoder I think for the target market, that is not a possibility here. Most people posting job listings are not developers (but are marketing/HR/recruiters), and therefore are unlikely to have GitHub accounts, etc. Passwords are currently hashed with bcrypt and stored with salts according to best security practices.

**Comment by groovecoder** [comment]
Agree the risk is low.

Still 👍 for getting rid of passwords and switching to GitHub + LinkedIn OAuth if possible.

**Comment by groovecoder** [comment]
Someone on the internet closed my open source software issue?! That's it - I'm forking!! 😜

**Comment by vlucas** [comment]
"Pull Requests Welcome" :p
